"""
Theme catalog for ALFRED-MK-VIII.
Houses structured ThemeDefinitions for classic, rogues gallery, and ops skins.
"""
from __future__ import annotations

from core.ui.themes.schema import (
    ChromeDefinition,
    IdentityDefinition,
    PaletteDefinition,
    SpeechFlavour,
    SubjectValueMode,
    ThemeDefinition,
    ThreatLevels,
)

# ── 1. DEFAULT BATCAVE (Wayne Classic) ───────────────────────────────────────
DEFAULT_BATCAVE = ThemeDefinition(
    id="dossier",
    display_name="DEFAULT BATCAVE",
    tagline="Standard Wayne Enterprises CRT interface with phosphor lavender accents",
    hex="#8e9bff",
    palette=PaletteDefinition(
        bg="#090a12",
        panel="#0d0f1e",
        panel2="#121528",
        panel_bg="rgba(13, 15, 30, 0.96)",
        border="#222748",
        border_b="#505bb5",
        border_a="#343a6b",
        pri="#8e9bff",
        pri_dim="#5463cc",
        pri_gho="#1a1d36",
        acc="#ff7390",
        acc2="#ffd166",
        green="#4ef2bb",
        green_d="#228562",
        red="#ff2a55",
        muted="#707ab0",
        muted_c="#ff3366",
        text="#e8ecff",
        text_dim="#707ab0",
        text_med="#a6b2f0",
        text_bright="#ffffff",
        white="#f4f6ff",
        dark="#05060a",
        bar_bg="#101222",
    ),
    identity=IdentityDefinition(
        subject_label="SUBJECT A-34",
        subject_value_mode=SubjectValueMode.KEEP_REAL,
        codename="ALFRED",
        incept_date="03/05/2026",
        function_line="TACTICAL PERSONAL ASSISTANT",
        mental_state="OPERATIONAL // ACTIVE",
        location_line="WAYNE MANOR // LOCALHOST",
        threat_header="THREAT ASSESSMENT",
        threat_levels=ThreatLevels(clear="★★★", low="★☆☆", elevated="★★☆", critical="★★★"),
        special_skills="[AI]  [SYS]  [SEC]  [AUDIO]",
        clearance_label="VERIFIED // ALPHA-1",
        affiliation_line="WAYNE ENTERPRISES • BATCOMPUTER",
    ),
    chrome=ChromeDefinition(
        status_prefix="SYS:",
        ready_line="ALFRED online.",
        idle_line="TARGET ACQUIRED: LOCAL",
        empty_archive="No archived directives found.",
        focus_locked_line="LOCKED ON TARGET",
        monitor_active_line="RECON FEED // OPTICAL",
        telemetry_header="SYS TELEMETRY",
        tab_telemetry="[ ◈ ]  TELEMETRY",
        tab_intel="[ ▤ ]  INTEL // NOTES",
        bio_scan_header="BIO-SCAN // FINGERPRINT",
        pose_track_header="TELEMETRY // POSE TRACK",
        window_title_suffix="BATCOMPUTER MATRIX",
        mini_hud_placeholder="Awaiting ALFRED response…",
    ),
)

# ── 2. BANE MODE (Venom Protocol) ───────────────────────────────────────────
BANE_MODE = ThemeDefinition(
    id="vector",
    display_name="BANE MODE",
    tagline="Heavy venom green CRT tactical terminal engineered for dominance",
    hex="#a8ff3e",
    palette=PaletteDefinition(
        bg="#060d07",
        panel="#09170b",
        panel2="#0f2613",
        panel_bg="rgba(9, 23, 11, 0.96)",
        border="#1d4724",
        border_b="#48a355",
        border_a="#285828",
        pri="#a8ff3e",
        pri_dim="#62b81d",
        pri_gho="#14290e",
        acc="#ffaa33",
        acc2="#ffd700",
        green="#a8ff3e",
        green_d="#509920",
        red="#ff3838",
        muted="#588554",
        muted_c="#ff4466",
        text="#dcfc9f",
        text_dim="#588554",
        text_med="#9de37d",
        text_bright="#ffffff",
        white="#f6ffea",
        dark="#030804",
        bar_bg="#0c1d0f",
    ),
    identity=IdentityDefinition(
        subject_label="SUBJECT — VENOM",
        subject_value_mode=SubjectValueMode.KEEP_REAL,
        codename="BANE",
        incept_date="03/05/2026",
        function_line="HEAVY TACTICAL COMBAT MATRIX",
        mental_state="UNSTOPPABLE // SURGING",
        location_line="PEÑA DURA // SECTOR-7",
        threat_header="DOMINANCE ASSESSMENT",
        threat_levels=ThreatLevels(clear="SUPPRESSED", low="SUBDUED", elevated="SURGING", critical="BREAK THE BAT"),
        special_skills="[BRUTE]  [VENOM]  [SIEGE]  [LEAGUE]",
        clearance_label="OVERRIDE // LEVEL-Ω",
        affiliation_line="PEÑA DURA • LEAGUE OF SHADOWS",
    ),
    chrome=ChromeDefinition(
        status_prefix="VENOM:",
        ready_line="Bane protocol activated. The shadows betray them.",
        idle_line="OCTANE FLOW // MAXIMUM READY",
        empty_archive="No broken targets recorded.",
        focus_locked_line="TARGET CRUSHED UNDER FOCUS",
        monitor_active_line="SURVEILLANCE GRID // OVERRUN",
        telemetry_header="VENOM METRICS",
        tab_telemetry="[ ◈ ]  COMBAT METRICS",
        tab_intel="[ ▤ ]  TARGET DOSSIER",
        bio_scan_header="BIO-FEED // VENOM INJECTION",
        pose_track_header="KINETIC MASS TRACKER",
        window_title_suffix="VENOM COMMAND CONSOLE",
        mini_hud_placeholder="Awaiting Bane directive…",
    ),
    speech_flavour=SpeechFlavour(enabled_default=False, address_form="commander"),
)

# ── 3. BATMAN BEYOND (Neo-Gotham Grid) ───────────────────────────────────────
BATMAN_BEYOND = ThemeDefinition(
    id="beyond",
    display_name="BATMAN BEYOND",
    tagline="High-contrast Neo-Gotham cyberpunk red with razor crimson telemetry",
    hex="#ff0037",
    palette=PaletteDefinition(
        bg="#070103",
        panel="#0d0205",
        panel2="#18040a",
        panel_bg="rgba(13, 2, 5, 0.96)",
        border="#3b0813",
        border_b="#ff0037",
        border_a="#660d1f",
        pri="#ff0037",
        pri_dim="#b80028",
        pri_gho="#33000b",
        acc="#00d4ff",
        acc2="#38bdf8",
        green="#00d4ff",
        green_d="#0284c7",
        red="#ff0037",
        muted="#8a2538",
        muted_c="#ff0037",
        text="#ffebef",
        text_dim="#8a2538",
        text_med="#ff758f",
        text_bright="#ffffff",
        white="#fff0f3",
        dark="#040002",
        bar_bg="#140308",
    ),
    identity=IdentityDefinition(
        subject_label="TERRY • CALLSIGN BEYOND",
        subject_value_mode=SubjectValueMode.KEEP_REAL,
        codename="BEYOND",
        incept_date="03/05/2039",
        function_line="NEO-GOTHAM CYBERNETIC COWL",
        mental_state="OVERDRIVE // LINKED",
        location_line="NEO-GOTHAM // SKYLINE-9",
        threat_header="CITY THREAT MATRIX",
        threat_levels=ThreatLevels(clear="STREETS QUIET", low="LOCAL PUNK", elevated="JOKERZ SPIKE", critical="CRIME SPREE"),
        special_skills="[ROCKET]  [STEALTH]  [NEURAL]  [OPTIC]",
        clearance_label="WAYNE TECH // 2039-B",
        affiliation_line="WAYNE-POWERED • NEO-GOTHAM GRID",
    ),
    chrome=ChromeDefinition(
        status_prefix="BEYOND:",
        ready_line="Suit systems synced. Terry online.",
        idle_line="ROOFTOP SCANNER // ACTIVE",
        empty_archive="Neo-Gotham logs cleared.",
        focus_locked_line="OPTICAL CAMOUFLAGE ENGAGED",
        monitor_active_line="HUD FEED // STREET CAM",
        telemetry_header="SUIT TELEMETRY",
        tab_telemetry="[ ◈ ]  SUIT SENSORS",
        tab_intel="[ ▤ ]  NEO-GOTHAM INTEL",
        bio_scan_header="RETINAL SCAN // CYBER-OPTIC",
        pose_track_header="NANOSUIT KINEMATICS",
        window_title_suffix="NEO-GOTHAM TACTICAL HUD",
        mini_hud_placeholder="Awaiting Terry telemetry…",
    ),
    speech_flavour=SpeechFlavour(enabled_default=False, address_form="Terry"),
)

# ── 4. JOKER (Clown Prince of Crime) ─────────────────────────────────────────
JOKER = ThemeDefinition(
    id="joker",
    display_name="JOKER",
    tagline="Deranged neon acid purple and toxic smile green with manic flair",
    hex="#b537f2",
    palette=PaletteDefinition(
        bg="#09030e",
        panel="#13071c",
        panel2="#1d0a2b",
        panel_bg="rgba(19, 7, 28, 0.96)",
        border="#381354",
        border_b="#b537f2",
        border_a="#581e82",
        pri="#b537f2",
        pri_dim="#7f1ea8",
        pri_gho="#28093b",
        acc="#2bf075",
        acc2="#ffdd00",
        green="#2bf075",
        green_d="#188f43",
        red="#ff1744",
        muted="#8c4b9b",
        muted_c="#ff1744",
        text="#fae8ff",
        text_dim="#8c4b9b",
        text_med="#d580f7",
        text_bright="#ffffff",
        white="#fcf4ff",
        dark="#050108",
        bar_bg="#170824",
    ),
    identity=IdentityDefinition(
        subject_label="PATIENT 0801 // SMILE",
        subject_value_mode=SubjectValueMode.THEMATIC_CODENAME,
        codename="THE JOKER",
        incept_date="04/01/1940",
        function_line="CHAOS THEATRE ORCHESTRATION",
        mental_state="MANIC // HILARIOUS",
        location_line="ACE CHEMICALS // UNKNOWN",
        threat_header="COMEDY PROJECTION",
        threat_levels=ThreatLevels(clear="CHUCKLE", low="GIGGLE", elevated="HYSTERIA", critical="WHY SO SERIOUS?"),
        special_skills="[LAUGH]  [ACID]  [CROWBAR]  [CARDS]",
        clearance_label="LAUGHTER // PERMITTED",
        affiliation_line="ARKHAM HA-HA QUARANTINE WING",
    ),
    chrome=ChromeDefinition(
        status_prefix="HA-HA:",
        ready_line="Why so serious? The joke is about to begin!",
        idle_line="PUNCHLINE PENDING // TICKING",
        empty_archive="All jokes delivered. No survivors.",
        focus_locked_line="LOCKED IN THE CARNIVAL RIDE",
        monitor_active_line="FUNHOUSE MIRROR FEED",
        telemetry_header="MANIA GAUGES",
        tab_telemetry="[ ◈ ]  JEST METRICS",
        tab_intel="[ ▤ ]  RABBLE NOTES",
        bio_scan_header="SMILE-METER // DENTISTRY",
        pose_track_header="JAPERY & ACROBATICS",
        window_title_suffix="FUNHOUSE COMMAND DECK",
        mini_hud_placeholder="Why so serious, sir?…",
    ),
)

# ── 5. RIDDLER (Enigma Routine) ──────────────────────────────────────────────
RIDDLER = ThemeDefinition(
    id="riddler",
    display_name="RIDDLER",
    tagline="Obsessive emerald cyber-green and electric enigma query yellow",
    hex="#00e676",
    palette=PaletteDefinition(
        bg="#030c07",
        panel="#06190e",
        panel2="#0a2917",
        panel_bg="rgba(6, 25, 14, 0.96)",
        border="#134728",
        border_b="#00e676",
        border_a="#1d6b3c",
        pri="#00e676",
        pri_dim="#00a353",
        pri_gho="#08381c",
        acc="#ffd600",
        acc2="#76ff03",
        green="#00e676",
        green_d="#008a47",
        red="#ff3d00",
        muted="#3d7d56",
        muted_c="#ffd600",
        text="#e0fceb",
        text_dim="#3d7d56",
        text_med="#69f0ae",
        text_bright="#ffffff",
        white="#f0fff6",
        dark="#020804",
        bar_bg="#082112",
    ),
    identity=IdentityDefinition(
        subject_label="ENIGMA ROUTINE #?",
        subject_value_mode=SubjectValueMode.THEMATIC_CODENAME,
        codename="EDWARD NIGMA",
        incept_date="10/19/1948",
        function_line="OBSESSIVE INTELLECTUAL SUPREMACY",
        mental_state="SOLVING // SUPERIOR",
        location_line="GOTHAM WATERFRONT // LAB-?",
        threat_header="RIDDLE DENSITY MATRIX",
        threat_levels=ThreatLevels(clear="TRIVIAL", low="PERPLEXING", elevated="OBSESSIVE", critical="UNSOLVABLE"),
        special_skills="[CIPHER]  [TRAP]  [LOGIC]  [MAZE]",
        clearance_label="IQ // 210 CERTIFIED",
        affiliation_line="NIGMA TECH CORP • PUZZLE CORE",
    ),
    chrome=ChromeDefinition(
        status_prefix="ENIGMA:",
        ready_line="Riddle me this: what assistant is completely infallible?",
        idle_line="COMPUTING PARADOX // WAITING",
        empty_archive="Every puzzle currently mastered.",
        focus_locked_line="CONUNDRUM LOCKED ON TARGET",
        monitor_active_line="PUZZLE BOX SURVEILLANCE",
        telemetry_header="ENIGMA LOGIC ENGINES",
        tab_telemetry="[ ◈ ]  LOGIC GATES",
        tab_intel="[ ▤ ]  CIPHER ARCHIVES",
        bio_scan_header="CEREBRAL // SYNAPSE TRACE",
        pose_track_header="CALCULATED LOCOMOTION",
        window_title_suffix="ENIGMA COMPUTING TERMINAL",
        mini_hud_placeholder="Riddle pending answer…",
    ),
)

# ── 6. MR. FREEZE (Sub-Zero Cryo) ────────────────────────────────────────────
MR_FREEZE = ThemeDefinition(
    id="mr_freeze",
    display_name="MR. FREEZE",
    tagline="Cryogenic frost-cyan and absolute zero deep glacier navy",
    hex="#00f5d4",
    palette=PaletteDefinition(
        bg="#020a10",
        panel="#051522",
        panel2="#092033",
        panel_bg="rgba(5, 21, 34, 0.96)",
        border="#0f3c5c",
        border_b="#00f5d4",
        border_a="#155582",
        pri="#00f5d4",
        pri_dim="#00aba0",
        pri_gho="#062e3d",
        acc="#70d6ff",
        acc2="#e0fbfc",
        green="#00f5d4",
        green_d="#008f82",
        red="#ff5470",
        muted="#3e758c",
        muted_c="#70d6ff",
        text="#e6fffa",
        text_dim="#3e758c",
        text_med="#79ffe9",
        text_bright="#ffffff",
        white="#f2fffc",
        dark="#01060a",
        bar_bg="#081c2c",
    ),
    identity=IdentityDefinition(
        subject_label="VICTOR • CRYO STATIS",
        subject_value_mode=SubjectValueMode.THEMATIC_CODENAME,
        codename="DR. FRIES",
        incept_date="02/01/1959",
        function_line="SUB-ZERO CRYOGENIC LIFE SUPPORT",
        mental_state="ISOLATED // COLD",
        location_line="GOTHAM CRYO CORP // SUB-LEVEL",
        threat_header="TEMPERATURE GRADIENT",
        threat_levels=ThreatLevels(clear="273 K (CHILL)", low="200 K (FROST)", elevated="100 K (FREEZE)", critical="0 K (ABSOLUTE)"),
        special_skills="[CRYO]  [SUIT]  [CHEM]  [PERMAFROST]",
        clearance_label="SUB-ZERO // STABLE",
        affiliation_line="GOTHAM CRYOGENICS • NORA PROTOCOL",
    ),
    chrome=ChromeDefinition(
        status_prefix="CRYO:",
        ready_line="Cryo suit pressurised. Heart of ice online.",
        idle_line="THERMAL FLUX // SUB-ZERO",
        empty_archive="Preserved specimens intact.",
        focus_locked_line="DEEP FREEZE FOCUS ACTIVE",
        monitor_active_line="INFRARED THERMAL SCAN",
        telemetry_header="COOLANT TELEMETRY",
        tab_telemetry="[ ◈ ]  CRYO CHAMBERS",
        tab_intel="[ ▤ ]  FORMULAE & RESEARCH",
        bio_scan_header="CORE TEMPERATURE // -50°C",
        pose_track_header="CRYO-EXOSKELETON DRIFT",
        window_title_suffix="CRYO-MAINFRAME TERMINAL",
        mini_hud_placeholder="Glacial stillness confirmed…",
    ),
)

# ── 7. TWO-FACE (Double-Entry Duality) ────────────────────────────────────────
TWO_FACE = ThemeDefinition(
    id="harvey_two_face",
    display_name="HARVEY TWO-FACE",
    tagline="Split scorched bronze-gold and charred courthouse obsidian slate",
    hex="#e0a96d",
    palette=PaletteDefinition(
        bg="#0c0a08",
        panel="#17120e",
        panel2="#241d17",
        panel_bg="rgba(23, 18, 14, 0.96)",
        border="#4a3a2d",
        border_b="#e0a96d",
        border_a="#6e5743",
        pri="#e0a96d",
        pri_dim="#a87a47",
        pri_gho="#302316",
        acc="#c8102e",
        acc2="#d4af37",
        green="#70a980",
        green_d="#456b50",
        red="#c8102e",
        muted="#7a6755",
        muted_c="#c8102e",
        text="#f7ede2",
        text_dim="#7a6755",
        text_med="#e8c7a2",
        text_bright="#ffffff",
        white="#fcf7f2",
        dark="#070504",
        bar_bg="#1d1612",
    ),
    identity=IdentityDefinition(
        subject_label="HARVEY DENT // DUALITY",
        subject_value_mode=SubjectValueMode.THEMATIC_CODENAME,
        codename="TWO-FACE",
        incept_date="08/01/1942",
        function_line="BINARY JUSTICE & COIN PROBABILITY",
        mental_state="SPLIT // 50-50",
        location_line="COURT OF APPEALS // CELL-2",
        threat_header="COIN PROBABILITY 50/50",
        threat_levels=ThreatLevels(clear="CLEAN HEADS", low="FLIPPING", elevated="SCARRED TAILS", critical="JUDGMENT CALL"),
        special_skills="[LAW]  [PISTOL]  [CHANCE]  [SPLIT]",
        clearance_label="DA SEAL // COMPROMISED",
        affiliation_line="DISTRICT ATTORNEY • TWO HARVEYS",
    ),
    chrome=ChromeDefinition(
        status_prefix="DUAL:",
        ready_line="Heads you live, tails you don't. The coin is in the air.",
        idle_line="EQUAL CHANCE // BALANCED",
        empty_archive="Case files dismissed.",
        focus_locked_line="PROBABILITY COLLAPSED // LOCKED",
        monitor_active_line="BALANCED JUSTICE SURVEILLANCE",
        telemetry_header="EQUILIBRIUM TELEMETRY",
        tab_telemetry="[ ◈ ]  PROBABILITY",
        tab_intel="[ ▤ ]  CASE ARCHIVES",
        bio_scan_header="DUAL FACE // SCAR INTEGRITY",
        pose_track_header="SYMMETRIC SKELETAL SENSORS",
        window_title_suffix="DUAL COURTHOUSE SYSTEM",
        mini_hud_placeholder="The coin lands on its edge…",
    ),
)

# ── 8. CATWOMAN (East End Rooftops) ──────────────────────────────────────────
CATWOMAN = ThemeDefinition(
    id="catwoman",
    display_name="CATWOMAN",
    tagline="Sleek nocturnal East End velvet violet and jewel diamond cyan",
    hex="#9d4edd",
    palette=PaletteDefinition(
        bg="#07040a",
        panel="#0f0917",
        panel2="#180e24",
        panel_bg="rgba(15, 9, 23, 0.96)",
        border="#361a52",
        border_b="#9d4edd",
        border_a="#52277d",
        pri="#9d4edd",
        pri_dim="#6d2ba8",
        pri_gho="#220b36",
        acc="#48cae4",
        acc2="#e0c3fc",
        green="#48cae4",
        green_d="#1d7a8c",
        red="#ff4d6d",
        muted="#714894",
        muted_c="#48cae4",
        text="#f3e8ff",
        text_dim="#714894",
        text_med="#c77dff",
        text_bright="#ffffff",
        white="#fcf7ff",
        dark="#040206",
        bar_bg="#130b1c",
    ),
    identity=IdentityDefinition(
        subject_label="SELINA • CALLSIGN CAT",
        subject_value_mode=SubjectValueMode.THEMATIC_CODENAME,
        codename="CATWOMAN",
        incept_date="04/01/1940",
        function_line="HIGH-VALUE INFILTRATION & ACQUISITIONS",
        mental_state="SLY // UNTOUCHABLE",
        location_line="EAST END // DIAMOND ROOFTOPS",
        threat_header="SURVEILLANCE EVASION",
        threat_levels=ThreatLevels(clear="PROWLING", low="SHADOWED", elevated="ALARM TRIGGERED", critical="CLEAN GETAWAY"),
        special_skills="[WHIP]  [BURGLARY]  [AGILITY]  [JEWELS]",
        clearance_label="LOCKPICK // 99.8%",
        affiliation_line="EAST END NETWORK • ROOFTOP RUNNERS",
    ),
    chrome=ChromeDefinition(
        status_prefix="CAT:",
        ready_line="Nine lives and counting. Claws retracted, ready to strike.",
        idle_line="CATWALKS CLEAR // UNSEEN",
        empty_archive="Vault contents already liberated.",
        focus_locked_line="SILENT VAULT BREACH // FOCUS ON",
        monitor_active_line="ROOFTOP INFRARED CAMERA",
        telemetry_header="STEALTH SENSORS",
        tab_telemetry="[ ◈ ]  AGILITY METRICS",
        tab_intel="[ ▤ ]  ACQUISITION TARGETS",
        bio_scan_header="FELINE AGILITY // TRACER",
        pose_track_header="ROOFTOP POSE BALANCE",
        window_title_suffix="EAST END SAFECRACKER HUD",
        mini_hud_placeholder="Prowling undetected…",
    ),
)

# ── 9. ARKHAM ASYLUM (Maximum Security Quarters) ─────────────────────────────
ARKHAM = ThemeDefinition(
    id="arkham",
    display_name="ARKHAM ASYLUM",
    tagline="Grim institutional asylum slate-green with clinical quarantine red",
    hex="#588157",
    palette=PaletteDefinition(
        bg="#070a08",
        panel="#0d1410",
        panel2="#141f19",
        panel_bg="rgba(13, 20, 16, 0.96)",
        border="#24382c",
        border_b="#588157",
        border_a="#344e41",
        pri="#588157",
        pri_dim="#3a5a3a",
        pri_gho="#16241a",
        acc="#f4a261",
        acc2="#e76f51",
        green="#588157",
        green_d="#2f4a30",
        red="#d62828",
        muted="#53695c",
        muted_c="#d62828",
        text="#e3ede6",
        text_dim="#53695c",
        text_med="#839c89",
        text_bright="#ffffff",
        white="#f0f5f2",
        dark="#030504",
        bar_bg="#0f1712",
    ),
    identity=IdentityDefinition(
        subject_label="INMATE RECORD #404",
        subject_value_mode=SubjectValueMode.THEMATIC_CODENAME,
        codename="ARKHAM WARDEN",
        incept_date="10/01/1921",
        function_line="PSYCHIATRIC RESTRAINT & ISOLATION",
        mental_state="STABLE // MEDICATED",
        location_line="ELIZABETH ARKHAM // BLOCK B",
        threat_header="CONTAINMENT INTEGRITY",
        threat_levels=ThreatLevels(clear="SEDATED", low="RESTLESS", elevated="CODE RED RIOT", critical="CELL BLOCK BREACH"),
        special_skills="[CURE]  [SEDATIVE]  [PADDED]  [LOCKDOWN]",
        clearance_label="ORDERLY // SEC-4",
        affiliation_line="ELIZABETH ARKHAM ASYLUM FOR THE CRIMINALLY INSANE",
    ),
    chrome=ChromeDefinition(
        status_prefix="ASYLUM:",
        ready_line="Maximum security grid online. All cells locked.",
        idle_line="CORRIDOR PATROL // ALL CLEAR",
        empty_archive="Incident logs locked in records room.",
        focus_locked_line="CELL BLOCK LOCKDOWN ACTIVE",
        monitor_active_line="ISOLATION WARD CAMS",
        telemetry_header="PATIENT VITALS",
        tab_telemetry="[ ◈ ]  CELL MONITORS",
        tab_intel="[ ▤ ]  PSYCH PROFILES",
        bio_scan_header="SEDATIVE LEVEL // 98.4%",
        pose_track_header="RESTRAINT JACKET MONITOR",
        window_title_suffix="ARKHAM SANITARIUM MAINFRAME",
        mini_hud_placeholder="Orderlies reporting all quiet…",
    ),
)

# ── 10. JUSTICE LEAGUE WATCHTOWER (Orbital Clean) ────────────────────────────
WATCHTOWER = ThemeDefinition(
    id="watchtower",
    display_name="WATCHTOWER OMNI",
    tagline="Clean deep orbital space vacuum with celestial satellite cyan and gold",
    hex="#00b4d8",
    palette=PaletteDefinition(
        bg="#030812",
        panel="#061224",
        panel2="#0a1d38",
        panel_bg="rgba(6, 18, 36, 0.96)",
        border="#12345e",
        border_b="#00b4d8",
        border_a="#1b4982",
        pri="#00b4d8",
        pri_dim="#0077b6",
        pri_gho="#072242",
        acc="#ffb703",
        acc2="#fb8500",
        green="#00f5d4",
        green_d="#008f82",
        red="#e63946",
        muted="#4b7094",
        muted_c="#ffb703",
        text="#e6f4fc",
        text_dim="#4b7094",
        text_med="#64c0eb",
        text_bright="#ffffff",
        white="#f2f9ff",
        dark="#010408",
        bar_bg="#09182e",
    ),
    identity=IdentityDefinition(
        subject_label="OPERATOR // ORBITAL LINK",
        subject_value_mode=SubjectValueMode.KEEP_REAL,
        codename="WATCHTOWER",
        incept_date="03/05/2026",
        function_line="GLOBAL THREAT INTERCEPTION & ORBITAL OPS",
        mental_state="VIGILANT // ORBITAL",
        location_line="GEOSYNCHRONOUS ORBIT // 35,786 KM",
        threat_header="GLOBAL THREAT LEVEL",
        threat_levels=ThreatLevels(clear="SURFACE NOMINAL", low="CONTINENTAL", elevated="PLANETARY ALERT", critical="EXTINCTION EVENT"),
        special_skills="[TELEPORT]  [ORBIT]  [DEFENSE]  [ARRAY]",
        clearance_label="FOUNDING MEMBER // JL-1",
        affiliation_line="JUSTICE LEAGUE ORBITAL WATCHTOWER",
    ),
    chrome=ChromeDefinition(
        status_prefix="WATCHTOWER:",
        ready_line="Watchtower uplink established. Global sensors active.",
        idle_line="ORBITAL SATELLITE ARRAY // LINKED",
        empty_archive="Global emergency ledger clear.",
        focus_locked_line="TARGET LOCKED VIA ORBITAL ARRAY",
        monitor_active_line="GLOBAL DOWNLINK RADAR",
        telemetry_header="WATCHTOWER SENSORS",
        tab_telemetry="[ ◈ ]  ORBITAL ARRAY",
        tab_intel="[ ▤ ]  GLOBAL INCIDENTS",
        bio_scan_header="ION DRIVE // SYNCHRONIZED",
        pose_track_header="GRAV-COMPENSATOR TELEMETRY",
        window_title_suffix="JUSTICE LEAGUE WATCHTOWER OMNI",
        mini_hud_placeholder="Scanning terrestrial transmissions…",
    ),
)

ALL_THEMES: tuple[ThemeDefinition, ...] = (
    DEFAULT_BATCAVE,
    BANE_MODE,
    BATMAN_BEYOND,
    JOKER,
    RIDDLER,
    MR_FREEZE,
    TWO_FACE,
    CATWOMAN,
    ARKHAM,
    WATCHTOWER,
)
